version: '3.3'

#
# The Firefly III Data Importer will ask you for the Firefly III URL and a "Client ID".
# You can generate the Client ID at http://localhost/profile (after registering)
# The Firefly III URL is: http://app:8080
#
# Other URL's will give 500 | Server Error
#

services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    networks:
      - firefly
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - '80:8080'
    depends_on:
      - db
  db:
    image: mariadb
    hostname: fireflyiiidb
    networks:
      - firefly
    restart: always
    env_file: .db.env
    volumes:
      - firefly_iii_db:/var/lib/mysql

  importer:
    image: fireflyiii/data-importer:latest
    hostname: importer
    networks:
      - firefly
    restart: always
    ports:
      - '81:8080'
    depends_on:
      - app
    env_file: .importer.env

volumes:
   firefly_iii_upload:
   firefly_iii_db:

networks:
  firefly:
    driver: bridge
